address.parser:
  simple: ^[0-9A-Za-z\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff\s]*
  address-with-comma: ^[A-Za-z0-9\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff\s]+[,]+[A-Za-z0-9\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff\s]*
  with-no: " no "
  break-pattern:
    default: \s\d
    with-no: \s(No)\s
    comma: \,
